### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by HungryLion1** [biden2020prez/lgflip-kosher#1]
Hi, would it be possible for you to make the batch files that you're using available for people to read, or do you want to keep it private. The benefit of that is, if someone has other apps that they want to add in then they can.
PS. I totally understand if you don't want to...

**Comment by SZRabinowitz** [comment]
Hi @HungryLion1. I would be happy to do that as long as you give me credit, but I don't think it will help, because you need all the files of the apks, which I don't want to share, because it'll be a hassle accessing them all.  

But if you still want the batch files let me know, and I'll get them.

**Comment by SZRabinowitz** [comment]
One more condition is that if you are releasing it to the public the apps need to be kosher. Also, if you want, you can just let me know what apps you want and I'll add them in for everyone. (and if you provide the APK I'll even give you credit).

**Comment by HungryLion1** [comment]
@biden2020prez I would be Happy to give you credit (just not sure how). Basically, I frequently setup peoples phones for them, e.g. put on apps, remove the browser etc. I already have a program which auto installs any apps I choose, but it only has the -r flag and not the -g. As for the commands, I simply made a batch file.
I don't know how to make a batch file with choices. That's what I'm looking for in your program. (you can just tell me how, without giving me your entire program files if you like) If you want to sent it privately LMK and I'll give you my email adress.

P.S. I really like the work that you do on the forum. Keep up the great work.

**Comment by SZRabinowitz** [comment]
@HungryLion1 Hi, sure that shouldn't be a problem. 

In terms of -g, just add it in the batch.
for example "adb shell pm install -g -r -d yourapp.apk"

In terms of choices, try to decode this. If you need help explaining it, let me know, and I will


:start
%SystemRoot%\System32\choice.exe /C YN /N /M "Do you want to install apps onto your phone?[Y/N]: "
if errorlevel 2 goto noApps1
if errorlevel 1 goto yesApps1
if not errorlevel 1 goto startError

:startError
ECHO Not an option, try again.
ECHO.
goto start

:noApps1
ECHO Okay, no problem.
PAUSE 
ECHO Enjoy
pause
exit /b

:yesApps1
ECHO Okay, let's get started.
PAUSE
ECHO. 
%SystemRoot%\System32\choice.exe /C YN /N /M " To access your apps, it is advisable to get Apps4Flip launcher. Would you like to install it?[Y/N]: "
if errorlevel 2 goto noLauncher
if errorlevel 1 goto yesLauncher
if not errorlevel 1 goto apps1Error

:apps1Error
ECHO Not an option, try again. 
ECHO. 
goto yesApps1

:noLauncher
ECHO. 
ECHO No problem.
PAUSE 
cls
goto allApps

:yesLauncher
ECHO.
ECHO 1. For LG Classic Flip, Wine 2 (L125dl)
ECHO 2. For LG Exalt (VN220, UN220)
ECHO 3. Never Mind, I don't want Apps4Flip Launcher
ECHO.


(the "if not errorlevel is in case someone presses ctrl+c and then "n", (try it and you'll understand)


P.S. Who are you on the forum?

**Comment by HungryLion1** [comment]
@biden2020prez  Thanks. I'll look into when I have a chance and try to decode it.

**Comment by SZRabinowitz** [comment]
@HungryLion1 Okay, good luck. If you need help let me know.

In terms of giving credit, that was if you make it public. (although that was only if I gave you the batch files, like this you wouldn't need to)

**Comment by SZRabinowitz** [comment]
Were you able to figure it out? You want me to help you?

**Comment by SZRabinowitz** [comment]
In one week I'm planning on closing this issue if there's no further response.

**Comment by SZRabinowitz** [comment]
I am now closing this issue as I haven't heard back from you. If you need any help, reach out, and I'll be glad to help
